INSERT INTO languages (language, tag) VALUES ('Abkhaz', 'ab');
INSERT INTO languages (language, tag) VALUES ('Acehnese', 'ace');
INSERT INTO languages (language, tag) VALUES ('Acholi', 'ach');
INSERT INTO languages (language, tag) VALUES ('Afrikaans', 'af');
INSERT INTO languages (language, tag) VALUES ('Albanian', 'sq');
INSERT INTO languages (language, tag) VALUES ('Alur', 'alz');
INSERT INTO languages (language, tag) VALUES ('Amharic', 'am');
INSERT INTO languages (language, tag) VALUES ('Arabic', 'ar');
INSERT INTO languages (language, tag) VALUES ('Armenian', 'hy');
INSERT INTO languages (language, tag) VALUES ('Assamese', 'as');
INSERT INTO languages (language, tag) VALUES ('Awadhi', 'awa');
INSERT INTO languages (language, tag) VALUES ('Aymara', 'ay');
INSERT INTO languages (language, tag) VALUES ('Azerbaijani', 'az');
INSERT INTO languages (language, tag) VALUES ('Balinese', 'ban');
INSERT INTO languages (language, tag) VALUES ('Bambara', 'bm');
INSERT INTO languages (language, tag) VALUES ('Bashkir', 'ba');
INSERT INTO languages (language, tag) VALUES ('Basque', 'eu');
INSERT INTO languages (language, tag) VALUES ('Batak Karo', 'btx');
INSERT INTO languages (language, tag) VALUES ('Batak Simalungun', 'bts');
INSERT INTO languages (language, tag) VALUES ('Batak Toba', 'bbc');
INSERT INTO languages (language, tag) VALUES ('Belarusian', 'be');
INSERT INTO languages (language, tag) VALUES ('Bemba', 'bem');
INSERT INTO languages (language, tag) VALUES ('Bengali', 'bn');
INSERT INTO languages (language, tag) VALUES ('Betawi', 'bew');
INSERT INTO languages (language, tag) VALUES ('Bhojpuri', 'bho');
INSERT INTO languages (language, tag) VALUES ('Bikol', 'bik');
INSERT INTO languages (language, tag) VALUES ('Bosnian', 'bs');
INSERT INTO languages (language, tag) VALUES ('Breton', 'br');
INSERT INTO languages (language, tag) VALUES ('Bulgarian', 'bg');
INSERT INTO languages (language, tag) VALUES ('Buryat', 'bua');
INSERT INTO languages (language, tag) VALUES ('Cantonese', 'yue');
INSERT INTO languages (language, tag) VALUES ('Catalan', 'ca');
INSERT INTO languages (language, tag) VALUES ('Cebuano', 'ceb');
INSERT INTO languages (language, tag) VALUES ('Chichewa', 'ny');
INSERT INTO languages (language, tag) VALUES ('Chinese (Simplified)', 'zh');
INSERT INTO languages (language, tag) VALUES ('Chinese (Traditional)', 'zh-TW');
INSERT INTO languages (language, tag) VALUES ('Chuvash', 'cv');
INSERT INTO languages (language, tag) VALUES ('Corsican', 'co');
INSERT INTO languages (language, tag) VALUES ('Crimean Tatar', 'crh');
INSERT INTO languages (language, tag) VALUES ('Croatian', 'hr');
INSERT INTO languages (language, tag) VALUES ('Czech', 'cs');
INSERT INTO languages (language, tag) VALUES ('Danish', 'da');
INSERT INTO languages (language, tag) VALUES ('Dhivehi', 'dv');
INSERT INTO languages (language, tag) VALUES ('Dinka', 'din');
INSERT INTO languages (language, tag) VALUES ('Dogri', 'doi');
INSERT INTO languages (language, tag) VALUES ('Dombe', 'dov');
INSERT INTO languages (language, tag) VALUES ('Dutch', 'nl');
INSERT INTO languages (language, tag) VALUES ('Dzongkha', 'dz');
INSERT INTO languages (language, tag) VALUES ('English', 'en');
INSERT INTO languages (language, tag) VALUES ('Esperanto', 'eo');
INSERT INTO languages (language, tag) VALUES ('Estonian', 'et');
INSERT INTO languages (language, tag) VALUES ('Ewe', 'ee');
INSERT INTO languages (language, tag) VALUES ('Fijian', 'fj');
INSERT INTO languages (language, tag) VALUES ('Filipino', 'tl');
INSERT INTO languages (language, tag) VALUES ('Finnish', 'fi');
INSERT INTO languages (language, tag) VALUES ('French', 'fr');
INSERT INTO languages (language, tag) VALUES ('Frisian', 'fy');
INSERT INTO languages (language, tag) VALUES ('Fulani', 'ff');
INSERT INTO languages (language, tag) VALUES ('Ga', 'gaa');
INSERT INTO languages (language, tag) VALUES ('Galician', 'gl');
INSERT INTO languages (language, tag) VALUES ('Georgian', 'ka');
INSERT INTO languages (language, tag) VALUES ('German', 'de');
INSERT INTO languages (language, tag) VALUES ('Greek', 'el');
INSERT INTO languages (language, tag) VALUES ('Guarani', 'gn');
INSERT INTO languages (language, tag) VALUES ('Gujarati', 'gu');
INSERT INTO languages (language, tag) VALUES ('Haitian Creole', 'ht');
INSERT INTO languages (language, tag) VALUES ('Hakha Chin', 'cnh');
INSERT INTO languages (language, tag) VALUES ('Hausa', 'ha');
INSERT INTO languages (language, tag) VALUES ('Hawaiian', 'haw');
INSERT INTO languages (language, tag) VALUES ('Hebrew', 'iw');
INSERT INTO languages (language, tag) VALUES ('Hiligaynon', 'hil');
INSERT INTO languages (language, tag) VALUES ('Hindi', 'hi');
INSERT INTO languages (language, tag) VALUES ('Hmong', 'hmn');
INSERT INTO languages (language, tag) VALUES ('Hungarian', 'hu');
INSERT INTO languages (language, tag) VALUES ('Hunsrik', 'hrx');
INSERT INTO languages (language, tag) VALUES ('Icelandic', 'is');
INSERT INTO languages (language, tag) VALUES ('Igbo', 'ig');
INSERT INTO languages (language, tag) VALUES ('Ilocano', 'ilo');
INSERT INTO languages (language, tag) VALUES ('Indonesian', 'id');
INSERT INTO languages (language, tag) VALUES ('Irish', 'ga');
INSERT INTO languages (language, tag) VALUES ('Italian', 'it');
INSERT INTO languages (language, tag) VALUES ('Japanese', 'ja');
INSERT INTO languages (language, tag) VALUES ('Javanese', 'jw');
INSERT INTO languages (language, tag) VALUES ('Kannada', 'kn');
INSERT INTO languages (language, tag) VALUES ('Kapampangan', 'pam');
INSERT INTO languages (language, tag) VALUES ('Kazakh', 'kk');
INSERT INTO languages (language, tag) VALUES ('Khmer', 'km');
INSERT INTO languages (language, tag) VALUES ('Kiga', 'cgg');
INSERT INTO languages (language, tag) VALUES ('Kinyarwanda', 'rw');
INSERT INTO languages (language, tag) VALUES ('Kituba', 'ktu');
INSERT INTO languages (language, tag) VALUES ('Konkani', 'gom');
INSERT INTO languages (language, tag) VALUES ('Korean', 'ko');
INSERT INTO languages (language, tag) VALUES ('Krio', 'kri');
INSERT INTO languages (language, tag) VALUES ('Kurdish (Kurmanji)', 'ku');
INSERT INTO languages (language, tag) VALUES ('Kurdish (Sorani)', 'ckb');
INSERT INTO languages (language, tag) VALUES ('Kyrgyz', 'ky');
INSERT INTO languages (language, tag) VALUES ('Lao', 'lo');
INSERT INTO languages (language, tag) VALUES ('Latgalian', 'ltg');
INSERT INTO languages (language, tag) VALUES ('Latin', 'la');
INSERT INTO languages (language, tag) VALUES ('Latvian', 'lv');
INSERT INTO languages (language, tag) VALUES ('Ligurian', 'lij');
INSERT INTO languages (language, tag) VALUES ('Limburgish', 'li');
INSERT INTO languages (language, tag) VALUES ('Lingala', 'ln');
INSERT INTO languages (language, tag) VALUES ('Lithuanian', 'lt');
INSERT INTO languages (language, tag) VALUES ('Lombard', 'lmo');
INSERT INTO languages (language, tag) VALUES ('Luganda', 'lg');
INSERT INTO languages (language, tag) VALUES ('Luo', 'luo');
INSERT INTO languages (language, tag) VALUES ('Luxembourgish', 'lb');
INSERT INTO languages (language, tag) VALUES ('Macedonian', 'mk');
INSERT INTO languages (language, tag) VALUES ('Maithili', 'mai');
INSERT INTO languages (language, tag) VALUES ('Makassar', 'mak');
INSERT INTO languages (language, tag) VALUES ('Malagasy', 'mg');
INSERT INTO languages (language, tag) VALUES ('Malay', 'ms');
INSERT INTO languages (language, tag) VALUES ('Malay (Jawi)', 'ms-Arab');
INSERT INTO languages (language, tag) VALUES ('Malayalam', 'ml');
INSERT INTO languages (language, tag) VALUES ('Maltese', 'mt');
INSERT INTO languages (language, tag) VALUES ('Maori', 'mi');
INSERT INTO languages (language, tag) VALUES ('Marathi', 'mr');
INSERT INTO languages (language, tag) VALUES ('Meadow Mari', 'chm');
INSERT INTO languages (language, tag) VALUES ('Meiteilon (Manipuri)', 'mni-Mtei');
INSERT INTO languages (language, tag) VALUES ('Minang', 'min');
INSERT INTO languages (language, tag) VALUES ('Mizo', 'lus');
INSERT INTO languages (language, tag) VALUES ('Mongolian', 'mn');
INSERT INTO languages (language, tag) VALUES ('Myanmar (Burmese)', 'my');
INSERT INTO languages (language, tag) VALUES ('Ndebele (South)', 'nr');
INSERT INTO languages (language, tag) VALUES ('Nepalbhasa (Newari)', 'new');
INSERT INTO languages (language, tag) VALUES ('Nepali', 'ne');
INSERT INTO languages (language, tag) VALUES ('Norwegian', 'no');
INSERT INTO languages (language, tag) VALUES ('Nuer', 'nus');
INSERT INTO languages (language, tag) VALUES ('Occitan', 'oc');
INSERT INTO languages (language, tag) VALUES ('Odia (Oriya)', 'or');
INSERT INTO languages (language, tag) VALUES ('Oromo', 'om');
INSERT INTO languages (language, tag) VALUES ('Pangasinan', 'pag');
INSERT INTO languages (language, tag) VALUES ('Papiamento', 'pap');
INSERT INTO languages (language, tag) VALUES ('Pashto', 'ps');
INSERT INTO languages (language, tag) VALUES ('Persian', 'fa');
INSERT INTO languages (language, tag) VALUES ('Polish', 'pl');
INSERT INTO languages (language, tag) VALUES ('Portuguese (Brazil)', 'pt');
INSERT INTO languages (language, tag) VALUES ('Punjabi (Gurmukhi)', 'pa');
INSERT INTO languages (language, tag) VALUES ('Punjabi (Shahmukhi)', 'pa-Arab');
INSERT INTO languages (language, tag) VALUES ('Quechua', 'qu');
INSERT INTO languages (language, tag) VALUES ('Romani', 'rom');
INSERT INTO languages (language, tag) VALUES ('Romanian', 'ro');
INSERT INTO languages (language, tag) VALUES ('Rundi', 'rn');
INSERT INTO languages (language, tag) VALUES ('Russian', 'ru');
INSERT INTO languages (language, tag) VALUES ('Samoan', 'sm');
INSERT INTO languages (language, tag) VALUES ('Sango', 'sg');
INSERT INTO languages (language, tag) VALUES ('Sanskrit', 'sa');
INSERT INTO languages (language, tag) VALUES ('Scots Gaelic', 'gd');
INSERT INTO languages (language, tag) VALUES ('Sepedi', 'nso');
INSERT INTO languages (language, tag) VALUES ('Serbian', 'sr');
INSERT INTO languages (language, tag) VALUES ('Sesotho', 'st');
INSERT INTO languages (language, tag) VALUES ('Seychellois Creole', 'crs');
INSERT INTO languages (language, tag) VALUES ('Shan', 'shn');
INSERT INTO languages (language, tag) VALUES ('Shona', 'sn');
INSERT INTO languages (language, tag) VALUES ('Sicilian', 'scn');
INSERT INTO languages (language, tag) VALUES ('Silesian', 'szl');
INSERT INTO languages (language, tag) VALUES ('Sindhi', 'sd');
INSERT INTO languages (language, tag) VALUES ('Sinhala', 'si');
INSERT INTO languages (language, tag) VALUES ('Slovak', 'sk');
INSERT INTO languages (language, tag) VALUES ('Slovenian', 'sl');
INSERT INTO languages (language, tag) VALUES ('Somali', 'so');
INSERT INTO languages (language, tag) VALUES ('Spanish', 'es');
INSERT INTO languages (language, tag) VALUES ('Sundanese', 'su');
INSERT INTO languages (language, tag) VALUES ('Swahili', 'sw');
INSERT INTO languages (language, tag) VALUES ('Swati', 'ss');
INSERT INTO languages (language, tag) VALUES ('Swedish', 'sv');
INSERT INTO languages (language, tag) VALUES ('Tajik', 'tg');
INSERT INTO languages (language, tag) VALUES ('Tamil', 'ta');
INSERT INTO languages (language, tag) VALUES ('Tatar', 'tt');
INSERT INTO languages (language, tag) VALUES ('Telugu', 'te');
INSERT INTO languages (language, tag) VALUES ('Tetum', 'tet');
INSERT INTO languages (language, tag) VALUES ('Thai', 'th');
INSERT INTO languages (language, tag) VALUES ('Tigrinya', 'ti');
INSERT INTO languages (language, tag) VALUES ('Tsonga', 'ts');
INSERT INTO languages (language, tag) VALUES ('Tswana', 'tn');
INSERT INTO languages (language, tag) VALUES ('Turkish', 'tr');
INSERT INTO languages (language, tag) VALUES ('Turkmen', 'tk');
INSERT INTO languages (language, tag) VALUES ('Twi', 'ak');
INSERT INTO languages (language, tag) VALUES ('Ukrainian', 'uk');
INSERT INTO languages (language, tag) VALUES ('Urdu', 'ur');
INSERT INTO languages (language, tag) VALUES ('Uyghur', 'ug');
INSERT INTO languages (language, tag) VALUES ('Uzbek', 'uz');
INSERT INTO languages (language, tag) VALUES ('Vietnamese', 'vi');
INSERT INTO languages (language, tag) VALUES ('Welsh', 'cy');
INSERT INTO languages (language, tag) VALUES ('Xhosa', 'xh');
INSERT INTO languages (language, tag) VALUES ('Yiddish', 'yi');
INSERT INTO languages (language, tag) VALUES ('Yoruba', 'yo');
INSERT INTO languages (language, tag) VALUES ('Yucatec Maya', 'yua');
INSERT INTO languages (language, tag) VALUES ('Zulu', 'zu');
INSERT INTO languages (language, tag) VALUES ('Hebrew', 'he');
INSERT INTO languages (language, tag) VALUES ('Javanese', 'jv');
INSERT INTO languages (language, tag) VALUES ('Chinese (Simplified)', 'zh-CN');
