// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: languages.sql

package db

import (
	"context"
)

const selectLanguagesById = `-- name: SelectLanguagesById :one
select id, language, tag from languages where id = $1
`

func (q *Queries) SelectLanguagesById(ctx context.Context, id int16) (Language, error) {
	row := q.db.QueryRowContext(ctx, selectLanguagesById, id)
	var i Language
	err := row.Scan(&i.ID, &i.Language, &i.Tag)
	return i, err
}
