// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Language struct {
	ID       int16  `json:"id"`
	Language string `json:"language"`
	Tag      string `json:"tag"`
}

type Permission struct {
	ID   int16  `json:"id"`
	Code string `json:"code"`
}

type Phrase struct {
	ID      int64 `json:"id"`
	TitleID int64 `json:"title_id"`
}

type Title struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	NumSubs      int16  `json:"num_subs"`
	OgLanguageID int16  `json:"og_language_id"`
}

type Translate struct {
	PhraseID   int64  `json:"phrase_id"`
	LanguageID int16  `json:"language_id"`
	Phrase     string `json:"phrase"`
	PhraseHint string `json:"phrase_hint"`
}

type User struct {
	ID             int64     `json:"id"`
	TitleID        int64     `json:"title_id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	OgLanguageID   int16     `json:"og_language_id"`
	NewLanguageID  int16     `json:"new_language_id"`
	Created        time.Time `json:"created"`
}

type UsersPermission struct {
	UserID       int64 `json:"user_id"`
	PermissionID int16 `json:"permission_id"`
}

type UsersPhrase struct {
	UserID        int64 `json:"user_id"`
	TitleID       int64 `json:"title_id"`
	PhraseID      int64 `json:"phrase_id"`
	LanguageID    int16 `json:"language_id"`
	PhraseCorrect int16 `json:"phrase_correct"`
}

type Voice struct {
	ID                     int16    `json:"id"`
	LanguageID             int16    `json:"language_id"`
	LanguageCodes          []string `json:"language_codes"`
	SsmlGender             string   `json:"ssml_gender"`
	Name                   string   `json:"name"`
	NaturalSampleRateHertz int16    `json:"natural_sample_rate_hertz"`
}
