// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Language struct {
	ID       int64  `json:"id"`
	Language string `json:"language"`
	Tag      string `json:"tag"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type Phrase struct {
	ID             int64  `json:"id"`
	TitleID        int64  `json:"title_id"`
	Phrase         string `json:"phrase"`
	Translates     string `json:"translates"`
	PhraseHint     string `json:"phrase_hint"`
	TranslatesHint string `json:"translates_hint"`
}

type Title struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	NumSubs      int32  `json:"num_subs"`
	LanguageID   int64  `json:"language_id"`
	OgLanguageID int64  `json:"og_language_id"`
}

type User struct {
	ID             int64     `json:"id"`
	TitleID        int64     `json:"title_id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	Flipped        bool      `json:"flipped"`
	OgLanguageID   int64     `json:"og_language_id"`
	NewLanguageID  int64     `json:"new_language_id"`
	Created        time.Time `json:"created"`
}

type UsersPermission struct {
	UserID       int64 `json:"user_id"`
	PermissionID int64 `json:"permission_id"`
}

type UsersPhrase struct {
	UserID         int64         `json:"user_id"`
	PhraseID       int64         `json:"phrase_id"`
	TitleID        int64         `json:"title_id"`
	PhraseCorrect  sql.NullInt64 `json:"phrase_correct"`
	FlippedCorrect sql.NullInt64 `json:"flipped_correct"`
}
