// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	DeleteTitleById(ctx context.Context, id int64) error
	DeleteTranslatesByLanguageId(ctx context.Context, arg DeleteTranslatesByLanguageIdParams) error
	DeleteUserById(ctx context.Context, id int64) error
	DeleteUserPermissionById(ctx context.Context, arg DeleteUserPermissionByIdParams) error
	InsertPhrases(ctx context.Context, titleID int64) (Phrase, error)
	InsertTitle(ctx context.Context, arg InsertTitleParams) (Title, error)
	InsertTranslates(ctx context.Context, arg InsertTranslatesParams) (Translate, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertUserPermission(ctx context.Context, arg InsertUserPermissionParams) (UsersPermission, error)
	ListLanguages(ctx context.Context) ([]Language, error)
	ListTitles(ctx context.Context, arg ListTitlesParams) ([]ListTitlesRow, error)
	ListTitlesByOgLanguage(ctx context.Context, arg ListTitlesByOgLanguageParams) ([]ListTitlesByOgLanguageRow, error)
	ListVoices(ctx context.Context) ([]Voice, error)
	SelectExistsTranslates(ctx context.Context, arg SelectExistsTranslatesParams) (bool, error)
	SelectLanguagesById(ctx context.Context, id int16) (Language, error)
	SelectPermissionByCode(ctx context.Context, code string) (Permission, error)
	SelectPhraseIdsByTitleId(ctx context.Context, titleID int64) ([]int64, error)
	SelectTitleById(ctx context.Context, id int64) (Title, error)
	SelectTranslatesByTitleIdLangId(ctx context.Context, arg SelectTranslatesByTitleIdLangIdParams) ([]Translate, error)
	SelectTranslatesWithCorrect(ctx context.Context, arg SelectTranslatesWithCorrectParams) ([]SelectTranslatesWithCorrectRow, error)
	SelectUserById(ctx context.Context, id int64) (User, error)
	SelectUserByName(ctx context.Context, name string) (User, error)
	SelectUserPermissions(ctx context.Context, userID int64) ([]string, error)
	SelectUsersPhrasesByCorrect(ctx context.Context, arg SelectUsersPhrasesByCorrectParams) ([]int64, error)
	SelectUsersPhrasesByIds(ctx context.Context, arg SelectUsersPhrasesByIdsParams) (UsersPhrase, error)
	SelectVoiceById(ctx context.Context, id int16) (Voice, error)
	SelectVoicesByLanguageId(ctx context.Context, languageID int16) ([]Voice, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
	UpdateUsersPhrasesByThreeIds(ctx context.Context, arg UpdateUsersPhrasesByThreeIdsParams) (UsersPhrase, error)
}

var _ Querier = (*Queries)(nil)
