// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	DeleteTitleById(ctx context.Context, id int64) error
	DeleteUserById(ctx context.Context, id int64) error
	DeleteUserPermissionById(ctx context.Context, arg DeleteUserPermissionByIdParams) error
	InsertTitle(ctx context.Context, arg InsertTitleParams) (Title, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertUserPermission(ctx context.Context, arg InsertUserPermissionParams) (UsersPermission, error)
	ListTitles(ctx context.Context, arg ListTitlesParams) ([]ListTitlesRow, error)
	ListTitlesByLanguage(ctx context.Context, arg ListTitlesByLanguageParams) ([]ListTitlesByLanguageRow, error)
	SelectPermissionByCode(ctx context.Context, code string) (Permission, error)
	SelectTitleById(ctx context.Context, id int64) (Title, error)
	SelectUserById(ctx context.Context, id int64) (User, error)
	SelectUserByName(ctx context.Context, name string) (User, error)
	SelectUserPermissions(ctx context.Context, userID int64) ([]string, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
